name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: "0 */12 * * *"  # run every 12 hours
  workflow_dispatch:        # allow manual run from the Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch latest posts from SheLovesTechy (Blogger)
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://shelovestechy.blogspot.com/feeds/posts/default?alt=rss"
          max_post_count: 3
          remove_duplicates: true
          committer_username: "github-actions[bot]"
          committer_email: "41898282+github-actions[bot]@users.noreply.github.com"
